#!/bin/sh

 # Remove all tracks from cmus library without deleting any
 # files from the disk.
 cmus-remote -C clear

 # Scans the specified directories and adds contained music
 # files to the cmus library.
 cmus-remote -C "add ~/media/audio/mp3-downloaded"
 cmus-remote -C "add ~/media/audio/ogg-transcode"

 # Forces a full rescan of the entire library, refreshing
 # metadata and checking for changes in the files.
 cmus-remote -C "update-cache -f"
